version: "3.9"

services:
  app:
    build: .
    container_name: fintrack-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    extra_hosts:
      - "redis.local:host-gateway"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
    networks:
      default:
        aliases:
          - app.local

networks:
  default:
    name: fintrack-net